In [ ]:
import numpy as np
import pandas as pd
import transformers
from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline

In [ ]:
dataset=pd.read_csv('data.csv')
dataset.head()

Sentence Sentiment
0  The GeoSolutions technology will leverage Bene...  positive
1  $ESI on lows, down $1.50 to $2.50 BK a real po...  negative
2  For the last quarter of 2010 , Componenta 's n...  positive
3  According to the Finnish-Russian Chamber of Co...   neutral
4  The Swedish buyout firm has sold its remaining...   neutral

In [ ]:
dataset.shape

(5842, 2)

In [ ]:
dataset.isnull().sum()

Sentence     0
Sentiment    0
dtype: int64

In [ ]:
dataset.duplicated().sum()

6

In [ ]:
dataset.drop_duplicates(inplace=True)

In [ ]:
finbert=AutoModelForSequenceClassification.from_pretrained('yiyanghkust/finbert-tone',num_labels=3)
tokenizer=AutoTokenizer.from_pretrained('yiyanghkust/finbert-tone')
nlp=pipeline('sentiment-analysis',model=finbert,tokenizer=tokenizer)
results=dataset['Sentence'].apply(lambda x: nlp(x)[0])
dataset['pred_Sentiment']=results.apply(lambda x: x['label'].lower())

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json:   0%|          | 0.00/533 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/439M [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


vocab.txt:   0%|          | 0.00/226k [00:00<?, ?B/s]

In [ ]:
dataset

Sentence Sentiment  \
0     The GeoSolutions technology will leverage Bene...  positive   
1     $ESI on lows, down $1.50 to $2.50 BK a real po...  negative   
2     For the last quarter of 2010 , Componenta 's n...  positive   
3     According to the Finnish-Russian Chamber of Co...   neutral   
4     The Swedish buyout firm has sold its remaining...   neutral   
...                                                 ...       ...   
5837  RISING costs have forced packaging producer Hu...  negative   
5838  Nordic Walking was first used as a summer trai...   neutral   
5839  According shipping company Viking Line , the E...   neutral   
5840  In the building and home improvement trade , s...   neutral   
5841  HELSINKI AFX - KCI Konecranes said it has won ...  positive   

     pred_Sentiment  
0          positive  
1          negative  
2          positive  
3           neutral  
4           neutral  
...             ...  
5837       negative  
5838        neutral  
5839       negative  
5840       negative  
5841        neutral  

[5836 rows x 3 columns]

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
cm=confusion_matrix(dataset['Sentiment'],dataset['pred_Sentiment'])
accuracy=accuracy_score(dataset['Sentiment'],dataset['pred_Sentiment'])
print(cm)
print(accuracy)

[[ 523  313   24]
 [ 448 2560  116]
 [  67  815  970]]
0.6944825222755312
