In [ ]:
import numpy as np
import pandas as pd
import transformers
from transformers import BertTokenizer, BertForSequenceClassification, pipeline

In [ ]:
!file -bi all-data.csv
dataset=pd.read_csv('all-data.csv',encoding='iso-8859-1',names=['Sentiment','Text'])
dataset.head()

text/plain; charset=iso-8859-1


Sentiment                                               Text
0   neutral  According to Gran , the company has no plans t...
1   neutral  Technopolis plans to develop in stages an area...
2  negative  The international electronic industry company ...
3  positive  With the new production plant the company woul...
4  positive  According to the company 's updated strategy f...

In [ ]:
dataset.shape

(4846, 2)

In [ ]:
dataset.isnull().sum()

Sentiment    0
Text         0
dtype: int64

In [ ]:
dataset['Text'].duplicated().sum()

8

In [ ]:
dataset.drop_duplicates(subset=['Text'],keep='first',inplace=True)

In [ ]:
finbert=BertForSequenceClassification.from_pretrained('yiyanghkust/finbert-tone')
tokenizer=BertTokenizer.from_pretrained('yiyanghkust/finbert-tone')
nlp=pipeline('sentiment-analysis',model=finbert,tokenizer=tokenizer)
results=dataset['Text'].apply(lambda x: nlp(x)[0])
dataset['pred_Sentiment']=results.apply(lambda x: x['label'].lower())

In [ ]:
dataset

Sentiment                                               Text  \
0      neutral  According to Gran , the company has no plans t...   
1      neutral  Technopolis plans to develop in stages an area...   
2     negative  The international electronic industry company ...   
3     positive  With the new production plant the company woul...   
4     positive  According to the company 's updated strategy f...   
...        ...                                                ...   
4841  negative  LONDON MarketWatch -- Share prices ended lower...   
4842   neutral  Rinkuskiai 's beer sales fell by 6.5 per cent ...   
4843  negative  Operating profit fell to EUR 35.4 mn from EUR ...   
4844  negative  Net sales of the Paper segment decreased to EU...   
4845  negative  Sales in Finland decreased by 10.5 % in Januar...   

     pred_Sentiment  
0           neutral  
1           neutral  
2           neutral  
3          positive  
4          positive  
...             ...  
4841       negative  
4842       positive  
4843       negative  
4844       negative  
4845       negative  

[4838 rows x 3 columns]

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix
cm=confusion_matrix(dataset['Sentiment'],dataset['pred_Sentiment'])
accuracy=accuracy_score(dataset['Sentiment'],dataset['pred_Sentiment'])
print(cm)
print(accuracy)

[[ 413  177   14]
 [  60 2638  174]
 [  47  532  783]]
0.7924762298470442
