In [ ]:
import numpy as np
import pandas as pd
import transformers
from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline

In [ ]:
dataset=pd.read_csv('data.csv')
dataset.head()

Sentence Sentiment
0  The GeoSolutions technology will leverage Bene...  positive
1  $ESI on lows, down $1.50 to $2.50 BK a real po...  negative
2  For the last quarter of 2010 , Componenta 's n...  positive
3  According to the Finnish-Russian Chamber of Co...   neutral
4  The Swedish buyout firm has sold its remaining...   neutral

In [ ]:
dataset.shape

(5842, 2)

In [ ]:
dataset.isnull().sum()

Sentence     0
Sentiment    0
dtype: int64

In [ ]:
dataset.duplicated().sum()

6

In [ ]:
dataset.drop_duplicates(inplace=True)

In [ ]:
finbert=AutoModelForSequenceClassification.from_pretrained('ProsusAI/finbert',num_labels=3)
tokenizer=AutoTokenizer.from_pretrained('ProsusAI/finbert')
nlp=pipeline('sentiment-analysis',model=finbert,tokenizer=tokenizer)
results=dataset['Sentence'].apply(lambda x: nlp(x)[0])
dataset['pred_Sentiment']=results.apply(lambda x: x['label'].lower())

pytorch_model.bin:  12%|#1        | 52.4M/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/252 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

In [ ]:
dataset

Sentence Sentiment  \
0     The GeoSolutions technology will leverage Bene...  positive   
1     $ESI on lows, down $1.50 to $2.50 BK a real po...  negative   
2     For the last quarter of 2010 , Componenta 's n...  positive   
3     According to the Finnish-Russian Chamber of Co...   neutral   
4     The Swedish buyout firm has sold its remaining...   neutral   
...                                                 ...       ...   
5837  RISING costs have forced packaging producer Hu...  negative   
5838  Nordic Walking was first used as a summer trai...   neutral   
5839  According shipping company Viking Line , the E...   neutral   
5840  In the building and home improvement trade , s...   neutral   
5841  HELSINKI AFX - KCI Konecranes said it has won ...  positive   

     pred_Sentiment  
0          positive  
1          negative  
2          positive  
3           neutral  
4           neutral  
...             ...  
5837       negative  
5838        neutral  
5839       negative  
5840       negative  
5841       positive  

[5836 rows x 3 columns]

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix
cm=confusion_matrix(dataset['Sentiment'],dataset['pred_Sentiment'])
accuracy=accuracy_score(dataset['Sentiment'],dataset['pred_Sentiment'])
print(cm)
print(accuracy)

[[ 709  124   27]
 [ 610 2327  187]
 [  73  392 1387]]
0.7578821110349554
